# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/svg-hka/aurora_rtds/aurora_rtds.srcs/sources_1/ip/fifo_loop/fifo_loop.xci
# IP: The module: 'fifo_loop' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/svg-hka/aurora_rtds/aurora_rtds.srcs/sources_1/ip/fifo_loop/fifo_loop.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loop'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/svg-hka/aurora_rtds/aurora_rtds.srcs/sources_1/ip/fifo_loop/fifo_loop_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loop'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/svg-hka/aurora_rtds/aurora_rtds.srcs/sources_1/ip/fifo_loop/fifo_loop.xci
# IP: The module: 'fifo_loop' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/svg-hka/aurora_rtds/aurora_rtds.srcs/sources_1/ip/fifo_loop/fifo_loop.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loop'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/svg-hka/aurora_rtds/aurora_rtds.srcs/sources_1/ip/fifo_loop/fifo_loop_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_loop'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
