#
# Vivado (TM) v2016.1 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'rtds_axis'
#
# Generated by Vivado on Sun Jun 26 13:35:44 +0200 2016
# IP Build 1537824 on Fri Apr  8 04:28:57 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/two_flop_synchronizer.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/netlist/RTDS_InterfaceModule.ngc"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/rtds_axis_fsm_axis2rtds.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/rtds_axis_fsm_rtds2axis.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/rtds_axis_axi_slv.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/rtds_axis.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/component.xml"
#    "D:/svo/gtfpga/rtds/rtds_axis/ip/axis_data_fifo_0_1/axis_data_fifo_0.xci"
#    "D:/svo/gtfpga/rtds/rtds_axis/constraints/rtds_axis_ooc.xdc"
#    "D:/svo/gtfpga/rtds/rtds_axis/constraints/rtds_axis_clocks.xdc"
#    "D:/svo/gtfpga/rtds/rtds_axis/constraints/rtds_axis.xdc"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/villas.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/helpers.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/RTDS_InterfaceModule.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/top_tb.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/simulation/receive.txt"
#    "D:/svo/gtfpga/rtds/rtds_axis/simulation/send.txt"
#    "D:/svo/gtfpga/rtds/rtds_axis/simulation/top_tb_behav.wcfg"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/axis_delay.vhd"
#    "D:/svo/gtfpga/rtds/rtds_axis/hdl/txt_util.vhd"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/work"]"

# Create project
create_project rtds_axis "work" -part xc7vx485tffg1761-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects rtds_axis]
set_property "board_part" "xilinx.com:vc707:part0:1.2" $obj
set_property "corecontainer.enable" "1" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "None" $obj
set_property "target_language" "VHDL" $obj
set_property "target_simulator" "ModelSim" $obj
set_property "xpm_libraries" "XPM_CDC" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo/rtds_axisp_1.1"] [file normalize "$origin_dir/"] [file normalize "$origin_dir/../../axis_delay"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hdl/two_flop_synchronizer.vhd"]"\
 "[file normalize "$origin_dir/netlist/RTDS_InterfaceModule.ngc"]"\
 "[file normalize "$origin_dir/hdl/rtds_axis_fsm_axis2rtds.vhd"]"\
 "[file normalize "$origin_dir/hdl/rtds_axis_fsm_rtds2axis.vhd"]"\
 "[file normalize "$origin_dir/hdl/rtds_axis_axi_slv.vhd"]"\
 "[file normalize "$origin_dir/hdl/rtds_axis.vhd"]"\
 "[file normalize "$origin_dir/component.xml"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hdl/two_flop_synchronizer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/netlist/RTDS_InterfaceModule.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/hdl/rtds_axis_fsm_axis2rtds.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/rtds_axis_fsm_rtds2axis.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/rtds_axis_axi_slv.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/rtds_axis.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/component.xml"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP-XACT" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "rtds_axis" $obj

# Set IP repository paths
set obj [get_filesets axis_data_fifo_0]
set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo/rtds_axisp_1.1"] [file normalize "$origin_dir/"] [file normalize "$origin_dir/../../axis_delay"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ip/axis_data_fifo_0_1/axis_data_fifo_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/rtds_axis_ooc.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/constraints/rtds_axis_ooc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "processing_order" "EARLY" $file_obj
set_property "used_in" "synthesis implementation out_of_context" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/rtds_axis_clocks.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/constraints/rtds_axis_clocks.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "processing_order" "EARLY" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/rtds_axis.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/constraints/rtds_axis.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "processing_order" "LATE" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/hdl/villas.vhd"]"\
 "[file normalize "$origin_dir/hdl/helpers.vhd"]"\
 "[file normalize "$origin_dir/hdl/RTDS_InterfaceModule.vhd"]"\
 "[file normalize "$origin_dir/hdl/top_tb.vhd"]"\
 "[file normalize "$origin_dir/simulation/receive.txt"]"\
 "[file normalize "$origin_dir/simulation/send.txt"]"\
 "[file normalize "$origin_dir/simulation/top_tb_behav.wcfg"]"\
 "[file normalize "$origin_dir/hdl/axis_delay.vhd"]"\
 "[file normalize "$origin_dir/hdl/txt_util.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/hdl/villas.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "acs" $file_obj

set file "$origin_dir/hdl/helpers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "library" "acs" $file_obj

set file "$origin_dir/hdl/RTDS_InterfaceModule.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/top_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/axis_delay.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/txt_util.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "modelsim.log_all_signals" "0" $obj
set_property "modelsim.use_explicit_decl" "1" $obj
set_property "modelsim.vhdl_syntax" "93" $obj
set_property "top" "top_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xsim.elaborate.debug_level" "all" $obj
set_property "xsim.simulate.runtime" "200 us" $obj
set_property "xsim.simulate.uut" "/top_tb/UUT" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7vx485tffg1761-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7vx485tffg1761-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:rtds_axis"
