set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[16]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[17]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[18]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[19]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[20]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[21]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[22]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[23]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[24]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[25]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[26]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[27]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[28]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[29]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[30]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[31]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/m_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/m_axis_tlast]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/m_axis_tready]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/m_axis_tvalid]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[16]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[17]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[18]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[19]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[20]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[21]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[22]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[23]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[24]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[25]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[26]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[27]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[28]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[29]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[30]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[31]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/s_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/s_axis_tlast]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/s_axis_tready]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/s_axis_tvalid]

set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/irq_case]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/irq_ts]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/irq_overflow]

set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/CardDetected]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/LinkUp]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/UserFreeBank]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/UserLockBank]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[0]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[10]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[11]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[12]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[13]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[14]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[15]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[16]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[17]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[18]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[19]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[1]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[20]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[21]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[22]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[23]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[24]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[25]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[26]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[27]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[28]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[29]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[30]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[31]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[8]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/UserTxData[9]}]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/UserTxWr]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/irq_case]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[0]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[10]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[11]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[12]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[13]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[14]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[15]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[16]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[17]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[18]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[19]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[1]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[20]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[21]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[22]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[23]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[8]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_addr[9]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[0]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[10]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[11]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[12]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[13]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[14]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[15]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[16]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[17]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[18]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[19]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[1]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[20]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[21]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[22]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[23]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[24]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[25]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[26]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[27]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[28]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[29]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[30]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[31]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[8]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/rx_data[9]}]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/rx_valid]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/ts_pulse]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/tx_full]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/tx_inprogress]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[0]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[10]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[11]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[12]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[13]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[14]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[15]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[1]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[2]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[3]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[4]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[5]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[6]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[7]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[8]}]
set_property MARK_DEBUG true [get_nets {top_i/hier_0/rtds_axis_0/U0/version[9]}]

set_property MARK_DEBUG true [get_nets top_i/pcie_0/axi_pcie_0_INTX_MSI_Grant]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_0/MSI_Vector_Width[2]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_0/MSI_Vector_Width[1]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_0/MSI_Vector_Width[0]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[3]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[5]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[1]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[2]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[4]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[0]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[6]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/msi_irq[7]}]


set_property MARK_DEBUG true [get_nets top_i/pcie_0/axi_pcie_intc_0_INTX_MSI_Request]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[0]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[1]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[2]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[3]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[4]}]
set_property MARK_DEBUG true [get_nets top_i/pcie_0/axi_pcie_0_MSI_enable]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0/U0/ack_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {top_i/pcie_0/axi_pcie_intc_0/U0/ack_reg_n_0_[1]}]

set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/case_inreset_reg_n_0]
set_property MARK_DEBUG true [get_nets top_i/hier_0/rtds_axis_0/U0/case_running_reg_n_0]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list top_i/hier_0/rtds_axis_0/U0/IFM/Clk100M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[0]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[1]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[2]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[3]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[4]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[5]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[6]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[7]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[8]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[9]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[10]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[11]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[12]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[13]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[14]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[15]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[16]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[17]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[18]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[19]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[20]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[21]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[22]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[23]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[24]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[25]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[26]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[27]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[28]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[29]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[30]} {top_i/hier_0/axis_interconnect_M00_AXIS_TDATA[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list top_i/pcie_0/axi_pcie_0/U0/comp_axi_enhanced_pcie/comp_enhanced_core_top_wrap/axi_pcie_enhanced_core_top_i/pcie_7x_v2_0_2_inst/pcie_top_with_gt_top.gt_ges.gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/INT_USERCLK2_OUT]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 5 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {top_i/pcie_0/msi_irq[0]} {top_i/pcie_0/msi_irq[1]} {top_i/pcie_0/msi_irq[2]} {top_i/pcie_0/msi_irq[3]} {top_i/pcie_0/msi_irq[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_i/hier_0/rtds_axis_0_m_axis_TDATA[0]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[1]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[2]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[3]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[4]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[5]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[6]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[7]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[8]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[9]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[10]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[11]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[12]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[13]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[14]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[15]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[16]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[17]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[18]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[19]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[20]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[21]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[22]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[23]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[24]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[25]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[26]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[27]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[28]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[29]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[30]} {top_i/hier_0/rtds_axis_0_m_axis_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {top_i/hier_0/rtds_axis_0/U0/version[0]} {top_i/hier_0/rtds_axis_0/U0/version[1]} {top_i/hier_0/rtds_axis_0/U0/version[2]} {top_i/hier_0/rtds_axis_0/U0/version[3]} {top_i/hier_0/rtds_axis_0/U0/version[4]} {top_i/hier_0/rtds_axis_0/U0/version[5]} {top_i/hier_0/rtds_axis_0/U0/version[6]} {top_i/hier_0/rtds_axis_0/U0/version[7]} {top_i/hier_0/rtds_axis_0/U0/version[8]} {top_i/hier_0/rtds_axis_0/U0/version[9]} {top_i/hier_0/rtds_axis_0/U0/version[10]} {top_i/hier_0/rtds_axis_0/U0/version[11]} {top_i/hier_0/rtds_axis_0/U0/version[12]} {top_i/hier_0/rtds_axis_0/U0/version[13]} {top_i/hier_0/rtds_axis_0/U0/version[14]} {top_i/hier_0/rtds_axis_0/U0/version[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {top_i/hier_0/rtds_axis_0/U0/rx_data[0]} {top_i/hier_0/rtds_axis_0/U0/rx_data[1]} {top_i/hier_0/rtds_axis_0/U0/rx_data[2]} {top_i/hier_0/rtds_axis_0/U0/rx_data[3]} {top_i/hier_0/rtds_axis_0/U0/rx_data[4]} {top_i/hier_0/rtds_axis_0/U0/rx_data[5]} {top_i/hier_0/rtds_axis_0/U0/rx_data[6]} {top_i/hier_0/rtds_axis_0/U0/rx_data[7]} {top_i/hier_0/rtds_axis_0/U0/rx_data[8]} {top_i/hier_0/rtds_axis_0/U0/rx_data[9]} {top_i/hier_0/rtds_axis_0/U0/rx_data[10]} {top_i/hier_0/rtds_axis_0/U0/rx_data[11]} {top_i/hier_0/rtds_axis_0/U0/rx_data[12]} {top_i/hier_0/rtds_axis_0/U0/rx_data[13]} {top_i/hier_0/rtds_axis_0/U0/rx_data[14]} {top_i/hier_0/rtds_axis_0/U0/rx_data[15]} {top_i/hier_0/rtds_axis_0/U0/rx_data[16]} {top_i/hier_0/rtds_axis_0/U0/rx_data[17]} {top_i/hier_0/rtds_axis_0/U0/rx_data[18]} {top_i/hier_0/rtds_axis_0/U0/rx_data[19]} {top_i/hier_0/rtds_axis_0/U0/rx_data[20]} {top_i/hier_0/rtds_axis_0/U0/rx_data[21]} {top_i/hier_0/rtds_axis_0/U0/rx_data[22]} {top_i/hier_0/rtds_axis_0/U0/rx_data[23]} {top_i/hier_0/rtds_axis_0/U0/rx_data[24]} {top_i/hier_0/rtds_axis_0/U0/rx_data[25]} {top_i/hier_0/rtds_axis_0/U0/rx_data[26]} {top_i/hier_0/rtds_axis_0/U0/rx_data[27]} {top_i/hier_0/rtds_axis_0/U0/rx_data[28]} {top_i/hier_0/rtds_axis_0/U0/rx_data[29]} {top_i/hier_0/rtds_axis_0/U0/rx_data[30]} {top_i/hier_0/rtds_axis_0/U0/rx_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {top_i/hier_0/rtds_axis_0/U0/rx_addr[0]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[1]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[2]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[3]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[4]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[5]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[6]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[7]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[8]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[9]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[10]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[11]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[12]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[13]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[14]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[15]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[16]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[17]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[18]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[19]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[20]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[21]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[22]} {top_i/hier_0/rtds_axis_0/U0/rx_addr[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {top_i/hier_0/rtds_axis_0/U0/UserTxData[0]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[1]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[2]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[3]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[4]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[5]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[6]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[7]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[8]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[9]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[10]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[11]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[12]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[13]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[14]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[15]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[16]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[17]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[18]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[19]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[20]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[21]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[22]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[23]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[24]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[25]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[26]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[27]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[28]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[29]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[30]} {top_i/hier_0/rtds_axis_0/U0/UserTxData[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 6 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[2]} {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[3]} {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[4]} {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[5]} {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[6]} {top_i/hier_0/rtds_axis_0/U0/UserTxAdr[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {top_i/hier_0/rtds_axis_0/s_axis_tdata[0]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[1]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[2]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[3]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[4]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[5]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[6]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[7]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[8]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[9]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[10]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[11]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[12]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[13]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[14]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[15]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[16]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[17]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[18]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[19]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[20]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[21]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[22]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[23]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[24]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[25]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[26]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[27]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[28]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[29]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[30]} {top_i/hier_0/rtds_axis_0/s_axis_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {top_i/hier_0/rtds_axis_0/m_axis_tdata[0]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[1]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[2]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[3]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[4]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[5]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[6]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[7]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[8]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[9]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[10]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[11]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[12]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[13]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[14]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[15]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[16]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[17]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[18]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[19]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[20]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[21]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[22]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[23]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[24]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[25]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[26]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[27]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[28]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[29]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[30]} {top_i/hier_0/rtds_axis_0/m_axis_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list top_i/hier_0/axis_interconnect_M00_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list top_i/hier_0/axis_interconnect_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list top_i/hier_0/axis_interconnect_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list top_i/hier_0/rtds_axis_0/U0/CardDetected]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list top_i/hier_0/rtds_axis_0/U0/case_inreset_reg_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list top_i/hier_0/rtds_axis_0/U0/case_running_reg_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list top_i/hier_0/rtds_axis_0/irq_case]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list top_i/hier_0/rtds_axis_0/U0/irq_case]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list top_i/hier_0/rtds_axis_0/irq_overflow]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list top_i/hier_0/rtds_axis_0/irq_ts]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list top_i/hier_0/rtds_axis_0/U0/LinkUp]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list top_i/hier_0/rtds_axis_0/m_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list top_i/hier_0/rtds_axis_0/m_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list top_i/hier_0/rtds_axis_0/m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list top_i/hier_0/rtds_axis_0_m_axis_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list top_i/hier_0/rtds_axis_0_m_axis_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list top_i/hier_0/rtds_axis_0_m_axis_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list top_i/hier_0/rtds_axis_0/U0/rx_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list top_i/hier_0/rtds_axis_0/s_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list top_i/hier_0/rtds_axis_0/s_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list top_i/hier_0/rtds_axis_0/s_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list top_i/hier_0/rtds_axis_0/U0/ts_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list top_i/hier_0/rtds_axis_0/U0/tx_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list top_i/hier_0/rtds_axis_0/U0/tx_inprogress]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list top_i/hier_0/rtds_axis_0/U0/UserFreeBank]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list top_i/hier_0/rtds_axis_0/U0/UserLockBank]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list top_i/hier_0/rtds_axis_0/U0/UserTxWr]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 5 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[0]} {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[1]} {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[2]} {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[3]} {top_i/pcie_0/axi_pcie_intc_0_MSI_Vector_Num[4]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 4 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {top_i/hier_0/axis_interconnect_M01_AXIS_TKEEP[0]} {top_i/hier_0/axis_interconnect_M01_AXIS_TKEEP[1]} {top_i/hier_0/axis_interconnect_M01_AXIS_TKEEP[2]} {top_i/hier_0/axis_interconnect_M01_AXIS_TKEEP[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 4 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TKEEP[0]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TKEEP[1]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TKEEP[2]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TKEEP[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 32 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[0]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[1]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[2]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[3]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[4]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[5]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[6]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[7]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[8]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[9]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[10]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[11]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[12]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[13]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[14]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[15]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[16]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[17]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[18]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[19]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[20]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[21]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[22]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[23]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[24]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[25]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[26]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[27]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[28]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[29]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[30]} {top_i/hier_0/axi_dma_M_AXIS_MM2S1_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 32 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[0]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[1]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[2]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[3]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[4]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[5]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[6]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[7]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[8]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[9]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[10]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[11]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[12]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[13]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[14]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[15]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[16]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[17]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[18]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[19]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[20]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[21]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[22]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[23]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[24]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[25]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[26]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[27]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[28]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[29]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[30]} {top_i/hier_0/axis_interconnect_M01_AXIS_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 32 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[0]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[1]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[2]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[3]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[4]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[5]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[6]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[7]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[8]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[9]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[10]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[11]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[12]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[13]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[14]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[15]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[16]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[17]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[18]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[19]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[20]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[21]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[22]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[23]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[24]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[25]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[26]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[27]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[28]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[29]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[30]} {top_i/hier_0/axis_interconnect_M02_AXIS_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 32 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[0]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[1]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[2]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[3]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[4]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[5]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[6]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[7]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[8]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[9]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[10]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[11]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[12]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[13]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[14]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[15]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[16]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[17]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[18]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[19]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[20]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[21]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[22]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[23]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[24]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[25]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[26]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[27]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[28]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[29]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[30]} {top_i/hier_0/S_AXIS_S2MM1_1_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 32 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list {top_i/hier_0/S02_AXIS_1_TDATA[0]} {top_i/hier_0/S02_AXIS_1_TDATA[1]} {top_i/hier_0/S02_AXIS_1_TDATA[2]} {top_i/hier_0/S02_AXIS_1_TDATA[3]} {top_i/hier_0/S02_AXIS_1_TDATA[4]} {top_i/hier_0/S02_AXIS_1_TDATA[5]} {top_i/hier_0/S02_AXIS_1_TDATA[6]} {top_i/hier_0/S02_AXIS_1_TDATA[7]} {top_i/hier_0/S02_AXIS_1_TDATA[8]} {top_i/hier_0/S02_AXIS_1_TDATA[9]} {top_i/hier_0/S02_AXIS_1_TDATA[10]} {top_i/hier_0/S02_AXIS_1_TDATA[11]} {top_i/hier_0/S02_AXIS_1_TDATA[12]} {top_i/hier_0/S02_AXIS_1_TDATA[13]} {top_i/hier_0/S02_AXIS_1_TDATA[14]} {top_i/hier_0/S02_AXIS_1_TDATA[15]} {top_i/hier_0/S02_AXIS_1_TDATA[16]} {top_i/hier_0/S02_AXIS_1_TDATA[17]} {top_i/hier_0/S02_AXIS_1_TDATA[18]} {top_i/hier_0/S02_AXIS_1_TDATA[19]} {top_i/hier_0/S02_AXIS_1_TDATA[20]} {top_i/hier_0/S02_AXIS_1_TDATA[21]} {top_i/hier_0/S02_AXIS_1_TDATA[22]} {top_i/hier_0/S02_AXIS_1_TDATA[23]} {top_i/hier_0/S02_AXIS_1_TDATA[24]} {top_i/hier_0/S02_AXIS_1_TDATA[25]} {top_i/hier_0/S02_AXIS_1_TDATA[26]} {top_i/hier_0/S02_AXIS_1_TDATA[27]} {top_i/hier_0/S02_AXIS_1_TDATA[28]} {top_i/hier_0/S02_AXIS_1_TDATA[29]} {top_i/hier_0/S02_AXIS_1_TDATA[30]} {top_i/hier_0/S02_AXIS_1_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 32 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list {top_i/hier_0/S01_AXIS_1_TDATA[0]} {top_i/hier_0/S01_AXIS_1_TDATA[1]} {top_i/hier_0/S01_AXIS_1_TDATA[2]} {top_i/hier_0/S01_AXIS_1_TDATA[3]} {top_i/hier_0/S01_AXIS_1_TDATA[4]} {top_i/hier_0/S01_AXIS_1_TDATA[5]} {top_i/hier_0/S01_AXIS_1_TDATA[6]} {top_i/hier_0/S01_AXIS_1_TDATA[7]} {top_i/hier_0/S01_AXIS_1_TDATA[8]} {top_i/hier_0/S01_AXIS_1_TDATA[9]} {top_i/hier_0/S01_AXIS_1_TDATA[10]} {top_i/hier_0/S01_AXIS_1_TDATA[11]} {top_i/hier_0/S01_AXIS_1_TDATA[12]} {top_i/hier_0/S01_AXIS_1_TDATA[13]} {top_i/hier_0/S01_AXIS_1_TDATA[14]} {top_i/hier_0/S01_AXIS_1_TDATA[15]} {top_i/hier_0/S01_AXIS_1_TDATA[16]} {top_i/hier_0/S01_AXIS_1_TDATA[17]} {top_i/hier_0/S01_AXIS_1_TDATA[18]} {top_i/hier_0/S01_AXIS_1_TDATA[19]} {top_i/hier_0/S01_AXIS_1_TDATA[20]} {top_i/hier_0/S01_AXIS_1_TDATA[21]} {top_i/hier_0/S01_AXIS_1_TDATA[22]} {top_i/hier_0/S01_AXIS_1_TDATA[23]} {top_i/hier_0/S01_AXIS_1_TDATA[24]} {top_i/hier_0/S01_AXIS_1_TDATA[25]} {top_i/hier_0/S01_AXIS_1_TDATA[26]} {top_i/hier_0/S01_AXIS_1_TDATA[27]} {top_i/hier_0/S01_AXIS_1_TDATA[28]} {top_i/hier_0/S01_AXIS_1_TDATA[29]} {top_i/hier_0/S01_AXIS_1_TDATA[30]} {top_i/hier_0/S01_AXIS_1_TDATA[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 4 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list {top_i/hier_0/S_AXIS_S2MM1_1_TKEEP[0]} {top_i/hier_0/S_AXIS_S2MM1_1_TKEEP[1]} {top_i/hier_0/S_AXIS_S2MM1_1_TKEEP[2]} {top_i/hier_0/S_AXIS_S2MM1_1_TKEEP[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 4 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list {top_i/hier_0/S01_AXIS_1_TKEEP[0]} {top_i/hier_0/S01_AXIS_1_TKEEP[1]} {top_i/hier_0/S01_AXIS_1_TKEEP[2]} {top_i/hier_0/S01_AXIS_1_TKEEP[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 3 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list {top_i/pcie_0/axi_pcie_0/MSI_Vector_Width[0]} {top_i/pcie_0/axi_pcie_0/MSI_Vector_Width[1]} {top_i/pcie_0/axi_pcie_0/MSI_Vector_Width[2]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list {top_i/pcie_0/axi_pcie_intc_0/U0/ack_reg_n_0_[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list {top_i/pcie_0/axi_pcie_intc_0/U0/ack_reg_n_0_[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list top_i/hier_0/axi_dma_M_AXIS_MM2S1_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list top_i/hier_0/axi_dma_M_AXIS_MM2S1_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list top_i/hier_0/axi_dma_M_AXIS_MM2S1_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list top_i/pcie_0/axi_pcie_0_INTX_MSI_Grant]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe19]
set_property port_width 1 [get_debug_ports u_ila_1/probe19]
connect_debug_port u_ila_1/probe19 [get_nets [list top_i/pcie_0/axi_pcie_0_MSI_enable]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe20]
set_property port_width 1 [get_debug_ports u_ila_1/probe20]
connect_debug_port u_ila_1/probe20 [get_nets [list top_i/pcie_0/axi_pcie_intc_0_INTX_MSI_Request]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe21]
set_property port_width 1 [get_debug_ports u_ila_1/probe21]
connect_debug_port u_ila_1/probe21 [get_nets [list top_i/hier_0/axis_interconnect_M01_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe22]
set_property port_width 1 [get_debug_ports u_ila_1/probe22]
connect_debug_port u_ila_1/probe22 [get_nets [list top_i/hier_0/axis_interconnect_M01_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe23]
set_property port_width 1 [get_debug_ports u_ila_1/probe23]
connect_debug_port u_ila_1/probe23 [get_nets [list top_i/hier_0/axis_interconnect_M01_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe24]
set_property port_width 1 [get_debug_ports u_ila_1/probe24]
connect_debug_port u_ila_1/probe24 [get_nets [list top_i/hier_0/axis_interconnect_M02_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe25]
set_property port_width 1 [get_debug_ports u_ila_1/probe25]
connect_debug_port u_ila_1/probe25 [get_nets [list top_i/hier_0/axis_interconnect_M02_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe26]
set_property port_width 1 [get_debug_ports u_ila_1/probe26]
connect_debug_port u_ila_1/probe26 [get_nets [list top_i/hier_0/axis_interconnect_M02_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe27]
set_property port_width 1 [get_debug_ports u_ila_1/probe27]
connect_debug_port u_ila_1/probe27 [get_nets [list top_i/hier_0/S01_AXIS_1_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe28]
set_property port_width 1 [get_debug_ports u_ila_1/probe28]
connect_debug_port u_ila_1/probe28 [get_nets [list top_i/hier_0/S01_AXIS_1_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe29]
set_property port_width 1 [get_debug_ports u_ila_1/probe29]
connect_debug_port u_ila_1/probe29 [get_nets [list top_i/hier_0/S01_AXIS_1_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe30]
set_property port_width 1 [get_debug_ports u_ila_1/probe30]
connect_debug_port u_ila_1/probe30 [get_nets [list top_i/hier_0/S02_AXIS_1_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe31]
set_property port_width 1 [get_debug_ports u_ila_1/probe31]
connect_debug_port u_ila_1/probe31 [get_nets [list top_i/hier_0/S02_AXIS_1_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe32]
set_property port_width 1 [get_debug_ports u_ila_1/probe32]
connect_debug_port u_ila_1/probe32 [get_nets [list top_i/hier_0/S02_AXIS_1_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe33]
set_property port_width 1 [get_debug_ports u_ila_1/probe33]
connect_debug_port u_ila_1/probe33 [get_nets [list top_i/hier_0/S_AXIS_S2MM1_1_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe34]
set_property port_width 1 [get_debug_ports u_ila_1/probe34]
connect_debug_port u_ila_1/probe34 [get_nets [list top_i/hier_0/S_AXIS_S2MM1_1_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe35]
set_property port_width 1 [get_debug_ports u_ila_1/probe35]
connect_debug_port u_ila_1/probe35 [get_nets [list top_i/hier_0/S_AXIS_S2MM1_1_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_INT_USERCLK2_OUT]
